#!/bin/bash

msg=${1:-"Updated"}

git add --all && git commit -am "$msg" && git push origin main


#git tag v0.1.0 && git push origin v0.1.0 && GOPROXY=proxy.golang.org go list -m github.com/gbaski/oapi-krakend
