#!/bin/bash

msg=${1:-"Updated"}

git add --all && git commit -am "$msg" && git push origin main


#v=v0.2.4 && git tag $v  && git push origin $v && GOPROXY=proxy.golang.org go list -m github.com/gbaski/oapi-krakend@$v
